begin;

create extension if not exists pgcrypto;

-- LOCAL TEST BOOTSTRAP ONLY. Never apply this file to a linked or hosted project.
-- The hosted project predates the checked-in migration history. This minimum
-- schema exists only so a clean, isolated local database can replay the later
-- production migrations without consulting production data.
-- Hosted Supabase projects create public-schema objects with role grants that
-- the historical migrations rely on. The isolated bootstrap runs migrations
-- as postgres, so reproduce those defaults here and let RLS enforce access.
grant usage on schema public to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant execute on functions to anon, authenticated, service_role;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gps_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  subject text not null default 'Generelt',
  description text not null default '',
  topic text not null default '',
  questions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gps_runs_questions_array_check
    check (jsonb_typeof(questions) = 'array')
);

create index if not exists gps_runs_user_created_idx
  on public.gps_runs(user_id, created_at desc);

create table if not exists public.live_sessions (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.gps_runs(id) on delete cascade,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  pin text not null,
  status text not null default 'waiting',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists live_sessions_run_idx
  on public.live_sessions(run_id);
create index if not exists live_sessions_teacher_created_idx
  on public.live_sessions(teacher_id, created_at desc);
create index if not exists live_sessions_pin_status_idx
  on public.live_sessions(pin, status);

create table if not exists public.telemetry_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  participant_id uuid,
  session_id uuid,
  message text,
  created_at timestamptz not null default now()
);

create index if not exists telemetry_logs_created_idx
  on public.telemetry_logs(created_at desc);

create table if not exists public.session_students (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  student_name text not null,
  last_updated timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (session_id, student_name)
);

create or replace function public.set_core_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_core_updated_at();

drop trigger if exists gps_runs_set_updated_at on public.gps_runs;
create trigger gps_runs_set_updated_at
before update on public.gps_runs
for each row execute function public.set_core_updated_at();

drop trigger if exists live_sessions_set_updated_at on public.live_sessions;
create trigger live_sessions_set_updated_at
before update on public.live_sessions
for each row execute function public.set_core_updated_at();

alter table public.profiles enable row level security;
alter table public.gps_runs enable row level security;
alter table public.live_sessions enable row level security;
alter table public.telemetry_logs enable row level security;
alter table public.session_students enable row level security;

revoke all on public.profiles from public, anon, authenticated;
revoke all on public.gps_runs from public, anon, authenticated;
revoke all on public.live_sessions from public, anon, authenticated;
revoke all on public.telemetry_logs from public, anon, authenticated;
revoke all on public.session_students from public, anon, authenticated;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.gps_runs to authenticated;
grant select, insert, update, delete on public.live_sessions to authenticated;
grant all on public.profiles, public.gps_runs, public.live_sessions,
  public.telemetry_logs, public.session_students to service_role;
grant usage, select on sequence public.telemetry_logs_id_seq to service_role;

create policy profiles_select_own on public.profiles
for select to authenticated using (auth.uid() = id);
create policy profiles_insert_own on public.profiles
for insert to authenticated with check (auth.uid() = id);
create policy profiles_update_own on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create policy gps_runs_owner_select on public.gps_runs
for select to authenticated using (auth.uid() = user_id);
create policy gps_runs_owner_insert on public.gps_runs
for insert to authenticated with check (auth.uid() = user_id);
create policy gps_runs_owner_update on public.gps_runs
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy gps_runs_owner_delete on public.gps_runs
for delete to authenticated using (auth.uid() = user_id);

create policy live_sessions_owner_select on public.live_sessions
for select to authenticated
using (
  teacher_id = auth.uid()
  and exists (
    select 1 from public.gps_runs gr
    where gr.id = live_sessions.run_id and gr.user_id = auth.uid()
  )
);
create policy live_sessions_owner_insert on public.live_sessions
for insert to authenticated
with check (
  teacher_id = auth.uid()
  and exists (
    select 1 from public.gps_runs gr
    where gr.id = live_sessions.run_id and gr.user_id = auth.uid()
  )
);
create policy live_sessions_owner_update on public.live_sessions
for update to authenticated
using (teacher_id = auth.uid())
with check (teacher_id = auth.uid());
create policy live_sessions_owner_delete on public.live_sessions
for delete to authenticated using (teacher_id = auth.uid());

commit;
