/**
 * Original, fictional postløb content for the five expansion packages.
 *
 * This module is intentionally script-only: it is never imported by public
 * catalogue code. Answers, teacher checks and clue pieces are therefore only
 * rendered into protected PDF variants by the generator.
 */

const postArtwork = (slug) => Array.from(
  { length: 6 },
  (_, index) => `${slug}-post-${index + 1}.png`,
);

export const POSTLOEB_PACKAGES = [
  {
    slug: "kystbyens-forsyningsplan",
    version: "1.0",
    assetStem: "SkoleGPS_Kystbyens_forsyningsplan",
    subject: "Matematik",
    gradeLevel: "5.-6. klasse",
    duration: "60-70 min.",
    activityType: "Fysisk postløb",
    title: "Kystbyens forsyningsplan",
    subtitle: "En opfundet stormplan med seks matematiske beslutninger",
    mission: "Kystbyen skal have en rolig og gennemtænkt plan, inden markedet åbner. Regn, mål og begrund jer frem til den rigtige rute.",
    heroArtwork: "kystbyens-forsyningsplan-hero.png",
    stationArtwork: postArtwork("kystbyens-forsyningsplan"),
    materials: [
      "seks A4-poster",
      "holdark og blyanter",
      "linealer",
      "seks lærerplanbrikker",
      "et afsluttende kort med en blå streg og et fyr",
    ],
    preparation: [
      "Print elevmaterialet: forside, seks poster og holdark.",
      "Placér posterne i klasseværelset, ved borde eller langs en kort rute.",
      "Klip de seks planbrikker fra facitarket ud, og behold dem hos læreren.",
      "Læg det afsluttende kort ved den aftalte slutpost.",
    ],
    flow: [
      ["Start", "Fortæl, at stormplanen er opdigtet. Holdene skal forklare deres matematiske valg, ikke finde en virkelig bys beredskab."],
      ["Poster", "Giv cirka 6-7 minutter ved hver post. Udlever kun en planbrik, når holdet kan vise en beregning eller begrundelse."],
      ["Saml", "Læg brikkerne i posternes rækkefølge og læs den fælles besked. Brug derefter det afsluttende kort."],
      ["Opsamling", "Sammenlign mindst to strategier: en beregning med enheder og en kontrol af et resultat."],
    ],
    debrief: [
      "Hvilken post krævede mest kontrol af enheder?",
      "Hvordan vidste I, at en løsning passede til budgettet eller ruten?",
      "Hvilken alternativ strategi kunne give samme svar?",
    ],
    finalMessage: "FØLG DEN BLÅ STREG MOD FYRET.",
    finalInstruction: "Læs beskeden højt. Følg derefter den aftalte blå streg eller brug slutkortet som klassens sidste punkt.",
    stations: [
      {
        title: "Budgetskema",
        skill: "Addition og multiplikation med penge",
        prompt: "Kystbyen bestiller 12 madkasser à 18 kr., 8 juicekartoner à 9 kr. og betaler 30 kr. i levering. Budgettet er 330 kr. Hvad koster ordren, og hvor meget er der tilbage?",
        responsePrompt: "Vis begge delberegninger og skriv, hvad resten af budgettet er.",
        answer: "12 x 18 + 8 x 9 + 30 = 318 kr. Der er 12 kr. tilbage.",
        strategy: "Bed holdet vise begge delberegninger og markere, hvad budgettet bruges til.",
        clue: "FØLG",
      },
      {
        title: "Vandtanken",
        skill: "Brøkdel af et tal",
        prompt: "Reservebeholderen kan rumme 18 L og er fyldt 3/4 op. Hvor mange liter er der i beholderen, og hvor mange liter mangler der?",
        responsePrompt: "Tegn eller forklar, hvordan I deler 18 L i fire lige store dele.",
        answer: "18 x 3/4 = 13,5 L. Der mangler 4,5 L.",
        strategy: "Lad eleverne forklare, om de deler i fire dele før eller efter de ganger med tre.",
        clue: "DEN",
      },
      {
        title: "Sikkerhedsbåndet",
        skill: "Omkreds",
        prompt: "Et afmærket lagerområde er et rektangel på 9 m x 6 m. Hvor mange meter tape skal bruges hele vejen rundt?",
        responsePrompt: "Skriv den regning, der viser alle fire sider.",
        answer: "2 x (9 + 6) = 30 m.",
        strategy: "Spørg, hvorfor kun arealet ikke kan bruges her.",
        clue: "BLAA",
      },
      {
        title: "Rutekortet",
        skill: "Målestok og enhedsomregning",
        prompt: "På kortet svarer 1 cm til 250 m i virkeligheden. Den blå rute er 6,4 cm på kortet. Hvor lang er ruten?",
        responsePrompt: "Skriv svaret både i meter og kilometer, hvis I kan.",
        answer: "6,4 x 250 = 1.600 m = 1,6 km.",
        strategy: "Accepter meter eller kilometer, hvis omregningen er korrekt.",
        clue: "STREG",
      },
      {
        title: "Kranstatistikken",
        skill: "Data og brøk",
        prompt: "Ved havnen tælles 6 blå, 9 grønne, 3 røde og 6 gule både. Hvilken farve er hyppigst, og hvor stor en brøkdel er grønne både?",
        responsePrompt: "Find først det samlede antal både. Vis derefter, hvordan brøken kan forkortes.",
        answer: "Grøn er hyppigst. 9/24 = 3/8.",
        strategy: "Bed holdet finde det samlede antal før de forkorter brøken.",
        clue: "MOD",
      },
      {
        title: "Nødgeneratoren",
        skill: "Multiplikation og restmængde",
        prompt: "Der er 4 dunke med 7,5 L brændstof i hver. Generatoren bruger 2,5 L i timen og skal køre i 9 timer. Rækker brændstoffet?",
        responsePrompt: "Skriv en tydelig konklusion med enhed og forklaring.",
        answer: "Der er 30 L i alt. Der bruges 22,5 L. Ja, der er 7,5 L tilbage.",
        strategy: "Lad eleverne skrive en tydelig konklusion med enhed.",
        clue: "FYRET",
      },
    ],
  },
  {
    slug: "det-sidste-program",
    version: "1.0",
    assetStem: "SkoleGPS_Det_sidste_program",
    subject: "Dansk",
    gradeLevel: "5.-6. klasse",
    duration: "60-70 min.",
    activityType: "Fysisk postløb",
    title: "Det sidste program",
    subtitle: "Seks originale tekstspor før biografens premiere",
    mission: "Den lokale biografs program er gået i stykker. Læs, fortolk, skriv og giv respons, så klassen kan gøre programmet klar igen.",
    heroArtwork: "det-sidste-program-hero.png",
    stationArtwork: postArtwork("det-sidste-program"),
    materials: [
      "seks A4-poster med originale tekstkort",
      "holdark og et enkelt programudkast",
      "blyanter",
      "seks lærerbrikker til den afsluttende programtekst",
    ],
    preparation: [
      "Print elevmaterialet: forside, seks poster, holdark og programudkast.",
      "Placér posterne, så holdene kan begynde forskellige steder.",
      "Klip de seks programbrikker fra facitarket ud, og behold dem hos læreren.",
      "Aftal en rolig læseplads, hvor holdene kan give mundtlig respons.",
    ],
    flow: [
      ["Start", "Fortæl, at alle tekster og filmtitler er originale og opdigtede. Målet er at bruge tekstbeviser og præcist sprog."],
      ["Poster", "Giv cirka 7 minutter ved hver post. Bed holdet pege på ord eller sætninger, der begrunder deres svar."],
      ["Premiere", "Læg programbrikkerne i posternes rækkefølge og læs den færdige besked sammen."],
      ["Opsamling", "Del en formulering fra post 5 eller en forbedring fra post 6. Tal om, hvorfor den virker for modtageren."],
    ],
    debrief: [
      "Hvilket tekstbevis brugte I, da I fandt publikum for opslaget?",
      "Hvordan ændrer perspektiv en oplevelse af den samme hændelse?",
      "Hvilken oplysning gør en invitation brugbar?",
    ],
    finalMessage: "PROGRAMMET ER KLAR TIL PREMIERE NU.",
    finalInstruction: "Læs beskeden som klassens premiere. Lad hvert hold læse sin bedste programsætning højt.",
    stations: [
      {
        title: "Hvem taler teksten til?",
        skill: "Afsender, modtager og formål",
        prompt: "OPSLAG: 6.B: I morgen kl. 13.40 viser vi Skyggen på lærredet i Festsalen. Tag jeres klassekort med. - Filmholdet. INTERNT NOTAT: Billetvagter: Mød kl. 13.15 ved indgangen. Husk kassen med farvede billetter. - Mira. Hvilken tekst er til publikum? Skriv afsender, modtager og formål.",
        responsePrompt: "Peg på mindst to ord i teksten, der beviser jeres svar.",
        answer: "Opslaget er til publikum. Afsender: Filmholdet. Modtager: 6.B. Formål: at informere og invitere klassen til filmvisningen.",
        strategy: "Kræv, at holdet peger på ord i teksten som bevis.",
        clue: "PROGRAMMET",
      },
      {
        title: "Anmelderens spor",
        skill: "Skelne mellem ros og kritik",
        prompt: "Filmen startede stille, men da Amira fandt en nøgle i loftet, begyndte salen at hviske. Lyden af regn var filmens stærkeste virkemiddel; den gjorde loftet til en del af historien. Slutningen kom lidt hurtigt. Understreg anmelderens ros og sæt ring om kritikken.",
        responsePrompt: "Skriv den sætning, der viser ros, og den sætning, der viser kritik.",
        answer: "Ros: Lyden af regn var filmens stærkeste virkemiddel. Kritik: Slutningen kom lidt hurtigt.",
        strategy: "Tal om forskellen mellem tekstbevis og egen mening.",
        clue: "ER",
      },
      {
        title: "Kuffertens rækkefølge",
        skill: "Fortællestruktur og sammenhæng",
        prompt: "Sortér: A. I kufferten lå et program med et tomt felt. B. Amira fandt en nøgle bag den gamle lampe. C. Nøglen drejede let i den grønne kufferts lås. D. På gulvet så hun en grøn kuffert uden nøgle.",
        responsePrompt: "Skriv rækkefølgen og tilføj en forbindende sætning med fx først, derefter eller da.",
        answer: "D, B, C, A. En forbindende sætning kan fx begynde med Derefter eller Da.",
        strategy: "Bed holdet begrunde mindst en overgang.",
        clue: "KLAR",
      },
      {
        title: "To blikke på mørket",
        skill: "Perspektiv",
        prompt: "Jonas: Lysene slukkede, og jeg blev glad, for så kunne filmen begynde. Nanna: Lysene slukkede, og jeg greb min vens hånd, fordi jeg ikke kunne se døren. Hvad oplever begge? Hvordan er deres reaktion forskellig?",
        responsePrompt: "Skriv en sætning om det samme og en sætning om det forskellige.",
        answer: "Begge oplever, at lysene slukkes. Jonas er forventningsfuld og glad. Nanna er utryg eller har svært ved at orientere sig.",
        strategy: "Hold fast i, at samme hændelse kan fortælles forskelligt.",
        clue: "TIL",
      },
      {
        title: "Det formelle program",
        skill: "Skriftlig information",
        prompt: "Månen over Møllevej. Torsdag 8. maj. Kl. 17.00. Lille Sal. Fritidsfilmholdet. 42 minutter. Gratis adgang. Skriv to sætninger til et program.",
        responsePrompt: "Jeres tekst skal have titel, tid, sted, afsender, varighed og adgang.",
        answer: "Eksempel: Fritidsfilmholdet viser Månen over Møllevej torsdag 8. maj kl. 17.00 i Lille Sal. Filmen varer 42 minutter, og der er gratis adgang.",
        strategy: "Tjek især tid, sted, afsender og adgang.",
        clue: "PREMIERE",
      },
      {
        title: "Gør invitationen klar",
        skill: "Mundtlig respons",
        prompt: "Vi viser Månen over Møllevej torsdag. Kom til Lille Sal. Læs teksten højt for en makker. Find fire manglende oplysninger ved hjælp af station 5, og giv en konkret forbedring.",
        responsePrompt: "Skriv fire manglende oplysninger og den forbedring, I vil give.",
        answer: "Manglende oplysninger: klokkeslæt, arrangør, varighed og gratis adgang. Fx: Tilføj kl. 17.00, så publikum ved, hvornår.",
        strategy: "Lad lytteren sige forbedringen højt før den skrives.",
        clue: "NU",
      },
    ],
  },
  {
    slug: "the-pop-up-bookshop",
    version: "1.0",
    assetStem: "SkoleGPS_The_pop_up_bookshop",
    subject: "Engelsk",
    gradeLevel: "5.-7. klasse",
    duration: "60-70 min.",
    activityType: "Physical station trail",
    title: "The Pop-up Bookshop",
    subtitle: "Six English tasks for a friendly bookshop opening",
    mission: "A pop-up bookshop opens today. Work in English as you read, talk, write and recommend one book to a visitor.",
    heroArtwork: "the-pop-up-bookshop-hero.png",
    stationArtwork: postArtwork("the-pop-up-bookshop"),
    materials: [
      "six English station sheets",
      "team sheet and pencils",
      "six teacher clue cards",
      "a blue ending mark for the final shelf",
    ],
    preparation: [
      "Print the student material: cover, six stations and team sheet.",
      "Place the stations so teams can start at different points.",
      "Cut out the six clue cards from the answer key and keep them with the teacher.",
      "Put a blue mark or a final card at the agreed ending place.",
    ],
    flow: [
      ["Open the shop", "Tell the class that the books and the Brightbrook event are fictional. English is the working language during the trail."],
      ["Rotate", "Give about seven minutes at each station. At station 3, approve a short understandable dialogue rather than an accent."],
      ["Meet visitors", "Put the clue cards in station order, read the final message and let each team give one short recommendation."],
      ["Reflect", "Ask which words helped a customer choose the right book and which recommendation sounded most useful."],
    ],
    debrief: [
      "Which words in a book description helped you choose?",
      "What makes a recommendation clear and polite?",
      "How did you make sure your spoken dialogue was understandable?",
    ],
    finalMessage: "MEET ME AT THE BLUE SHELF.",
    finalInstruction: "Read the message together, go to the agreed blue mark, and let each team share one book recommendation.",
    stations: [
      {
        title: "Shelf detectives",
        skill: "Genre vocabulary",
        prompt: "A. The Laughing Llama: Lola the llama loses a purple sock on every page. Each short chapter ends with a silly problem. B. River Rangers: Two friends test the water in their town river and make a clean-up plan. The book gives facts and labelled diagrams. C. The Last Lantern: When the lights go out in Pine Street, Noor follows a tiny lantern through rain and dark streets. Match each title with funny story, information book, adventure.",
        responsePrompt: "Write one keyword from each description that proves your match.",
        answer: "A is a funny story. B is an information book. C is an adventure.",
        strategy: "Ask pupils to identify words such as facts, silly and dark streets.",
        clue: "MEET",
      },
      {
        title: "Find the right book",
        skill: "Reading for specific information",
        prompt: "Customer card: I am 11. I want a funny animal story with short chapters. I do not want a scary book. Choose one book and give two reasons.",
        responsePrompt: "Write two reasons in English from the book description.",
        answer: "The Laughing Llama, because it is an animal story, it is silly or funny, and it has short chapters.",
        strategy: "Require two textual English reasons.",
        clue: "ME",
      },
      {
        title: "Speak at the counter",
        skill: "Short conversation",
        prompt: "Customer: I am looking for a book about animals. Shopkeeper: Try The Laughing Llama. It has short chapters. Customer: Great. How much is it? Shopkeeper: It is 45 kroner. Act it out. Add a greeting and a thank-you, then swap roles.",
        responsePrompt: "Prepare your short dialogue before you speak it to the teacher.",
        answer: "A short dialogue with a greeting, request or question, recommendation with a reason, price and ending.",
        strategy: "Judge understandable communication, not accent.",
        clue: "AT",
      },
      {
        title: "Write the blurb",
        skill: "Short descriptive writing",
        prompt: "River Rangers. Information book. Two friends clean a river. 48 pages. Ages 9+. Write three sentences for the shelf label.",
        responsePrompt: "Include the title, topic or type, and who the book is for.",
        answer: "Example: River Rangers is an information book about two friends who clean a river. It has 48 pages and is for readers aged nine and up. I recommend it to children who care about nature.",
        strategy: "Check capitals and full stops after the content is clear.",
        clue: "THE",
      },
      {
        title: "Story Swap",
        skill: "Cultural meeting through a fictional medium",
        prompt: "FICTIONAL EVENT CARD: Brightbrook Library's Story Swap. Bring a book you enjoyed. Say one sentence about it, then choose another reader's recommendation. The children's corner is called the Reading Den. What must a visitor do? Write one polite question about Reading Den and one similarity with a class book basket.",
        responsePrompt: "Write your answer in English. Mark the one thing that is invented for this learning task.",
        answer: "Bring a book, say one sentence about it, and choose another recommendation. Example question: What is the Reading Den? Both places let readers share or choose books. Brightbrook is fictional.",
        strategy: "Make clear that Brightbrook is an invented learning universe, not a real library.",
        clue: "BLUE",
      },
      {
        title: "Recommendation note",
        skill: "Matching information to a need",
        prompt: "River Rangers: nature, 48 pages, ages 9+. Night House: mystery, 70 pages, ages 11+. Tiny Tigers: animal story, 32 pages, ages 7+. Customer: I want a non-scary 40-60-page nature book for a 10-year-old. Choose and write a two-sentence note.",
        responsePrompt: "Check every part of the customer's request before you choose.",
        answer: "River Rangers. Example: Try River Rangers. It is a 48-page nature book for readers aged nine and up.",
        strategy: "Check the requirements before the choice.",
        clue: "SHELF",
      },
    ],
  },
  {
    slug: "regnhavens-laboratorium",
    version: "1.0",
    assetStem: "SkoleGPS_Regnhavens_laboratorium",
    subject: "Natur/teknologi",
    gradeLevel: "5.-6. klasse",
    duration: "65-75 min.",
    activityType: "Fysisk postløb",
    title: "Regnhavens laboratorium",
    subtitle: "Seks forsigtige undersøgelser af vand, jord og regnhaver",
    mission: "Skolen vil bygge en lille regnhave. Brug fiktive modeldata, en enkel tegning og præcise ord til at give en forsigtig anbefaling.",
    heroArtwork: "regnhavens-laboratorium-hero.png",
    stationArtwork: postArtwork("regnhavens-laboratorium"),
    materials: [
      "seks A4-poster",
      "modeltegning, holdark og blyanter",
      "seks lærerbrikker",
      "valgfrit: to bakker og vand til en lærerdemo",
    ],
    preparation: [
      "Print elevmaterialet: forside, seks poster, modeltegning og holdark.",
      "Placér posterne, så holdene kan begynde forskellige steder.",
      "Klip de seks laboratoriebrikker fra facitarket ud, og behold dem hos læreren.",
      "Hvis I laver demoen, brug to ens bakker. Pakken kan løses helt papirbaseret.",
    ],
    flow: [
      ["Start", "Fortæl, at målingerne er fiktive modeldata og ikke målinger fra skolens gård. Holdene skal sige nøjagtigt, hvad data viser."],
      ["Poster", "Giv cirka 7 minutter ved hver post. Bed holdene vise deres udregning, piltegning eller forsigtige formulering, før de får en brik."],
      ["Saml", "Læg brikkerne i posternes rækkefølge og læs den fælles besked. Brug den som afsæt for en forsigtig anbefaling."],
      ["Opsamling", "Spørg hvad en model kan pege på, og hvad der stadig skulle undersøges på den virkelige skolegrund."],
    ],
    debrief: [
      "Hvad måler denne model, og hvad måler den ikke?",
      "Hvorfor er ordene i denne model vigtige i en konklusion?",
      "Hvordan kan et overløb være en sikkerhedsløsning?",
    ],
    finalMessage: "REGNVAND KAN SIVE NED I JORDEN.",
    finalInstruction: "Læs beskeden sammen. Lad hvert hold give en kort, forsigtig anbefaling med afsæt i modeldataene.",
    stations: [
      {
        title: "Den fair undersøgelse",
        skill: "Variable i en undersøgelse",
        prompt: "To ens bakker får hver 300 mL vand. De har samme jord, størrelse, hældning og hældetid. Bakke A har bar jord; bakke B har løvdække. Hvad ændrer undersøgelsen, og nævn tre ting, der holdes ens.",
        responsePrompt: "Skriv den ændrede variabel og tre ting, der holdes ens.",
        answer: "Den ændrede variabel er overfladedækket. Konstant kan være vandmængde, jord, bakkestørrelse, hældning, hældetid.",
        strategy: "Hjælp holdet med at skelne mellem det, der ændres, og det, der måles.",
        clue: "REGNVAND",
      },
      {
        title: "Afstrømningsdata",
        skill: "Aflæse og sammenligne data",
        prompt: "Efter fem minutter er der opsamlet 180 mL afstrømning fra bar jord og 95 mL fra jord med løvdække. Hvor stor er forskellen?",
        responsePrompt: "Skriv forskellen og beskriv, hvilken overflade der havde mindst målt afstrømning.",
        answer: "Forskellen er 85 mL. Jord med løvdække havde mindst målt afstrømning.",
        strategy: "Bed holdet formulere, hvilken overflade der havde mindst målt afstrømning.",
        clue: "KAN",
      },
      {
        title: "Hvad viser data - og hvad viser de ikke?",
        skill: "Præcis konklusion",
        prompt: "Begge bakker fik 300 mL. Beregn, hvor meget vand der ikke blev målt som afstrømning efter fem minutter i hver bakke.",
        responsePrompt: "Skriv en konklusion, der bruger ordene ikke målt som afstrømning.",
        answer: "Bar jord: 120 mL. Jord med løvdække: 205 mL. Det skal omtales som vand, der ikke blev målt som afstrømning.",
        strategy: "Godkend kun formuleringen ikke målt som afstrømning, ikke at vandet automatisk sivede ned.",
        clue: "SIVE",
      },
      {
        title: "Vandets sikre vej",
        skill: "Enkel model",
        prompt: "Tegn pile på modellen: tagrende til lav, beplantet fordybning til gennemtrængelig jord til overløb væk fra bygningen. Vis både den normale vej og vejen ved for meget vand.",
        responsePrompt: "Brug mindst fire pile og forklar, hvor det ekstra vand skal hen.",
        answer: "Normal vej: tagrende, beplantet fordybning, gennemtrængelig jord. Ved for meget vand går det til et overløb væk fra bygningen.",
        strategy: "Forklar, at overløb er en sikkerhedsløsning, ikke en fejl.",
        clue: "NED",
      },
      {
        title: "Plantens rolle",
        skill: "Planters optagelse af vand",
        prompt: "Hvilken del af planten optager normalt vand fra jorden: blomsterblade, rodhår på rødderne eller frugter?",
        responsePrompt: "Skriv svaret og tegn en lille pil på roddelen i jeres model.",
        answer: "Rodhår på rødderne.",
        strategy: "Knyt svaret til tegningen under jorden fra station 4.",
        clue: "I",
      },
      {
        title: "Sig det præcist",
        skill: "Evidensbaseret forklaring",
        prompt: "Vælg det udsagn, data faktisk understøtter: A. I denne model havde løvdække 85 mL mindre målt afstrømning. B. Alle regnhaver stopper altid oversvømmelser. C. Blade får vand til at forsvinde.",
        responsePrompt: "Skriv bogstavet og forklar, hvorfor ordene i denne model er vigtige.",
        answer: "A. I denne model havde løvdække 85 mL mindre målt afstrømning.",
        strategy: "Spørg, hvorfor i denne model er en vigtig afgrænsning.",
        clue: "JORDEN",
      },
    ],
  },
  {
    slug: "kufferten-fra-kobstaden",
    version: "1.0",
    assetStem: "SkoleGPS_Kufferten_fra_kobstaden",
    subject: "Historie",
    gradeLevel: "5.-6. klasse",
    duration: "60-70 min.",
    activityType: "Fysisk postløb",
    title: "Kufferten fra Købstaden",
    subtitle: "Seks opfundne kildespor til en ægte kildekritisk øvelse",
    mission: "Et museum har fundet en kuffert med tydeligt konstruerede kort fra den fiktive by Havnekøbing. Skeln mellem belæg, tolkning og gæt, før I laver en ærlig museumslabel.",
    heroArtwork: "kufferten-fra-kobstaden-hero.png",
    stationArtwork: postArtwork("kufferten-fra-kobstaden"),
    materials: [
      "seks A4-poster med tydeligt mærkede fiktive kort",
      "tidslinjestribe, holdark og blyanter",
      "seks lærerbrikker",
    ],
    preparation: [
      "Print elevmaterialet: forside, seks poster, tidslinjestribe og holdark.",
      "Placér posterne, så holdene kan begynde forskellige steder.",
      "Klip de seks museumsbrikker fra facitarket ud, og behold dem hos læreren.",
      "Sig fra start, at Havnekøbing, personerne, årstallene og kortene er opfundne rekonstruktioner.",
    ],
    flow: [
      ["Åbn kufferten", "Fortæl, at alle kort er opfundne for at øve historisk undersøgelse. De er ikke virkelige kilder."],
      ["Poster", "Giv cirka 7 minutter ved hver post. Kræv et konkret kortbevis, før en museumsbrik udleveres."],
      ["Saml", "Læg brikkerne i posternes rækkefølge og læs den fælles besked. Lad derefter holdene forklare, hvad en kilde kan og ikke kan vise alene."],
      ["Opsamling", "Sammenlign to fiktive kilder. Tal om afsender, tidspunkt, formål og perspektiv før man drager en stor konklusion."],
    ],
    debrief: [
      "Hvad kan en enkelt fiktiv kilde støtte, og hvad kan den ikke bevise alene?",
      "Hvordan kan to beskrivelser af samme marked være forskellige uden at den ene nødvendigvis lyver?",
      "Hvilke ord gør en museumslabel ærlig om sin usikkerhed?",
    ],
    finalMessage: "HISTORIEN BLIVER TYDELIGERE NÅR VI UNDERSØGER.",
    finalInstruction: "Læs beskeden sammen og lad hvert hold nævne en ting, en kilde kan vise, og en ting den ikke kan bevise alene.",
    stations: [
      {
        title: "Tidslinjen",
        skill: "Kronologi",
        prompt: "FIKTIVE KORT. Sortér: A. Postkort, 1898: I dag blev de nye lygter tændt på Torvet. B. Butiksseddel, 1917: 12 sække mel modtaget ved kajen. C. Fototekst, 1949: Børn venter på bussen ved Torvet. D. Plakat, 1976: Åbning af Havnekøbings fælleshus på lørdag.",
        responsePrompt: "Skriv rækkefølgen og årstallene i en tidslinje.",
        answer: "A, B, C, D. 1898, 1917, 1949, 1976.",
        strategy: "Bed holdet begrunde med årstal, ikke antagelser om indholdet.",
        clue: "HISTORIEN",
      },
      {
        title: "Hvem skrev hvad?",
        skill: "Kildetype, afsender og modtager",
        prompt: "FIKTIV ARKIVØVELSE. Match: A. Brev fra Sofie til hendes bror, 1917. B. Kommunal meddelelse til byens borgere, 1931. C. Museumslabel skrevet til besøgende, 2026.",
        responsePrompt: "Skriv kildetype, afsender og modtager for hvert kort.",
        answer: "A: privat brev, Sofie, hendes bror. B: offentlig meddelelse, kommunen, borgerne. C: senere museumstolkning, museet, besøgende.",
        strategy: "Brug formuleringen i den fiktive arkivøvelse.",
        clue: "BLIVER",
      },
      {
        title: "Samme marked, to oplevelser",
        skill: "Perspektiv",
        prompt: "FIKTIVE DAGBOGSKORT. Kurvemager Else, 3. juni 1934: Markedet var travlt. Jeg solgte alle mine kurve før middag. Poul, 10 år, 3. juni 1934: Markedet var så tæt, at jeg mistede min mors hånd et øjeblik. Hvad er den fælles hændelse, og hvordan er deres oplevelser forskellige?",
        responsePrompt: "Skriv en fælles hændelse og brug et ord eller en sætning fra hvert kort som bevis.",
        answer: "Begge beskriver markedet. Else oplever travlhed og salg positivt. Poul oplever trængsel og utryghed.",
        strategy: "Kræv et ord eller en sætning som bevis fra hvert kort.",
        clue: "TYDELIGERE",
      },
      {
        title: "Kajens to fortællinger",
        skill: "Sammenligne kilder",
        prompt: "FIKTIVE KORT. Kommunalt referat, 2. maj 1952: Den nye kaj åbnede i dag. Varerne kunne flyttes hurtigere end før. Arbejderens note, 2. maj 1952: Den nye kaj åbnede i dag, men den første dag gik langsomt, mens alle lærte de nye ramper at kende.",
        responsePrompt: "Skriv en ting, kortene er enige om, og en ting, de vurderer forskelligt.",
        answer: "Enighed: kajen åbnede 2. maj 1952. Forskel: kommunen fremhæver hurtigere arbejde, arbejderen beskriver en langsom første dag.",
        strategy: "Forklar, at forskellig vurdering ikke nødvendigvis betyder, at nogen lyver.",
        clue: "NAAR",
      },
      {
        title: "Før og nu",
        skill: "Historisk sammenligning",
        prompt: "FIKTIVE KORT. Butiksskilt, 1934: Hos Færgekøbmanden: brød, lampeolie og sytråd. Plakat, 2026: Bytorvet: lån en elcykel, lad telefonen og få en kop kaffe. Skriv en forandring og en kontinuitet, som kortene kan støtte.",
        responsePrompt: "Brug mindst et ord fra begge kort i jeres begrundelse.",
        answer: "Forandring: fra lampeolie til telefon- eller elcykelopladning. Kontinuitet: et lokalt sted tilbyder varer eller tjenester.",
        strategy: "Brug ord fra begge kort, ikke frie gæt.",
        clue: "VI",
      },
      {
        title: "Museets ærlige label",
        skill: "Kildekritisk formidling",
        prompt: "Skriv en label på 25-45 ord til Sofies fiktive brev fra 1917. Den skal have kildetype, årstal, en påstand kortet støtter og en usikkerhed.",
        responsePrompt: "Brug ordene fiktivt og kan ikke alene bevise i jeres label.",
        answer: "Eksempel: Fiktivt brev fra Sofie, 1917. Brevet fortæller, at varer blev flyttet ved den gamle kaj. Det viser Sofies oplevelse, men kan ikke alene bevise, hvordan alle i Havnekøbing arbejdede.",
        strategy: "Tjek skellet mellem belæg og tolkning.",
        clue: "UNDERSØGER",
      },
    ],
  },
];
