export type GradeBand = "indskoling" | "mellemtrin" | "udskoling";

export type SubjectProfile = {
  commonGoalsIntro: string;
  courseIdeasByBand?: Partial<Record<GradeBand, string[]>>;
  courseIdeas: string[];
  focusAreas: string[];
  activityIdeas: string[];
  productIdeas: string[];
};

const naturalScienceActivities = [
  "forsøg, observationer, faglige samtaler og fælles opsamling",
  "feltarbejde, modelbygning, datanoter og forklaringsøvelser",
  "stationsarbejde, begrebskort, undersøgelser og korte præsentationer",
  "praktiske målinger, makkerforklaringer, tegninger og klassediskussion",
  "hypoteser, test, resultattabeller og faglig konklusion",
  "casearbejde, modeller, videoeksempler og elevproducerede forklaringer",
  "undersøgelsesværksted, feedback, repetition og kobling til hverdagen",
  "miniprojekt, vejledning, produktarbejde og afsluttende fremlæggelse",
];

const naturalScienceProducts = [
  "forsøgsrapport med kort konklusion",
  "model med faglig forklaring",
  "faglig forklaring med tegning eller diagram",
  "kort video eller præsentation",
  "undersøgelsesplakat med resultater",
  "begrebskort med eksempler",
  "mundtlig forklaring med fagord",
  "miniprojekt med dokumentation",
];

export const genericCommonGoalsIntro =
  "Årsplanen tager udgangspunkt i fagets kompetenceområder og fordeler årets forløb i overskuelige perioder med tydelige mål, aktiviteter og evaluering.";

export const subjectProfiles: Record<string, SubjectProfile> = {
  Dansk: {
    commonGoalsIntro:
      "I dansk arbejder eleverne med læsning, fremstilling, fortolkning og kommunikation. Årsplanen lægger op til tydelige forløb, hvor eleverne undersøger tekster, producerer egne udtryk og taler fagligt om sprog.",
    courseIdeasByBand: {
      indskoling: [
        "Bogstaver, lyd og læseglæde",
        "Fortællinger med billeder",
        "Rim, remser og sproglege",
        "Min første fagtekst",
        "Samtale og lytning",
        "Små tekster fra hverdagen",
      ],
      mellemtrin: [
        "Læselyst og læsestrategier",
        "Fortællinger med virkning",
        "Sprog, debat og holdninger",
        "Fortolkning i fællesskab",
        "Fremstilling med modtagerblik",
        "Medier, genrer og multimodale tekster",
      ],
      udskoling: [
        "Noveller og analyse",
        "Argumentation og debat",
        "Dokumentar, medier og vinkling",
        "Litteraturhistoriske nedslag",
        "Essay og personlig stemme",
        "Prøveforberedende portfolio",
      ],
    },
    courseIdeas: [
      "Læselyst og læsestrategier",
      "Fortællinger med virkning",
      "Sprog, debat og holdninger",
      "Fortolkning i fællesskab",
      "Fremstilling med modtagerblik",
      "Medier, genrer og multimodale tekster",
      "Mundtlighed og præsentation",
      "Årets danskfaglige portfolio",
    ],
    focusAreas: [
      "læsestrategier, tekstsamtaler og ordforråd",
      "komposition, synsvinkel, miljø og sproglige virkemidler",
      "påstande, belæg, appelformer og modtagerbevidsthed",
      "tema, symboler, citater og tekstnære begrundelser",
      "skriveproces, respons, revision og tydelig struktur",
      "genretræk, billedsprog, lyd, layout og digitale udtryk",
      "stemme, kropssprog, disposition og faglig respons",
      "refleksion, udvælgelse, progression og faglige mål",
    ],
    activityIdeas: [
      "fælles læsning, makkerdialoger, tekstmarkering og læselog",
      "skriveøvelser, modeltekster, responsrunde og tekstproduktion",
      "debatkort, mundtlige fremlæggelser, kildeblik og skriveproces",
      "litteratursamtaler, citatjagt, analysemodel og fælles opsamling",
      "skriveværksted, feedbackpar, mini-lektioner og omskrivning",
      "genrejagt, multimodal produktion, billedanalyse og kort fremlæggelse",
      "taleøvelser, optagelse, responskort og præsentationstræning",
      "portfolioarbejde, elevsamtaler, refleksionsark og udstilling",
    ],
    productIdeas: [
      "kort tekstsamling med respons",
      "mundtlig præsentation",
      "læselog med faglige noter",
      "responsrunde og bearbejdet tekst",
      "debatindlæg eller tale",
      "multimodal produktion med kort analyse",
      "portfolio-side med årsrefleksion",
      "fortolkningsnotat med citater",
    ],
  },
  Matematik: {
    commonGoalsIntro:
      "I matematik arbejder eleverne med problemløsning, ræsonnement, modellering og faglige begreber. Årsplanen lægger op til undersøgende aktiviteter, træning af strategier og anvendelse i hverdagsnære situationer.",
    courseIdeasByBand: {
      indskoling: [
        "Tal og tællestrategier",
        "Former og mønstre",
        "Måling i hverdagen",
        "Regnehistorier",
        "Data med klassen",
        "Matematik med konkrete materialer",
      ],
      mellemtrin: [
        "Tal og regnestrategier",
        "Geometri i hverdagen",
        "Måling og enheder",
        "Data og diagrammer",
        "Brøker og decimaltal",
        "Problemløsning i praksis",
      ],
      udskoling: [
        "Algebra og ligninger",
        "Lineære funktioner",
        "Procent og økonomi",
        "Statistik og sandsynlighed",
        "Geometri og trigonometri",
        "Matematiske modeller",
      ],
    },
    courseIdeas: [
      "Tal, strategier og mønstre",
      "Geometri i praksis",
      "Data og chance",
      "Problemløsning og modeller",
      "Brøker, procent og forhold",
      "Måling og enheder",
      "Algebraiske sammenhænge",
      "Matematik i virkelige cases",
    ],
    focusAreas: [
      "repræsentationer, forklaringer og strategivalg",
      "geometriske begreber, tegning, måling og argumentation",
      "tabeller, diagrammer, gennemsnit, udfald og vurderinger",
      "modellering, ræsonnement, valg af metoder og præcis kommunikation",
      "sammenhænge mellem brøker, procent, decimaltal og forhold",
      "målemetoder, overslag, præcision og enhedsskift",
      "mønstre, variable, regneregler og faglige forklaringer",
      "problemløsning, data, antagelser og vurdering af resultater",
    ],
    activityIdeas: [
      "undersøgende opgaver, fælles gennemgange, træningsloops og makkersnak",
      "opmåling, konstruktion, digitale skitser og forklaringer ved tavlen",
      "dataindsamling, diagramværksted, eksperimenter og klassekonklusioner",
      "åbne problemer, gruppestrategier, feedback og fælles løsninger",
      "kortspil, procentcases, visuelle modeller og selvstændig træning",
      "praktisk måling, overslagsøvelser, værkstedsopgaver og tjekspørgsmål",
      "mønsterjagt, funktionstabeller, parforklaringer og mini-beviser",
      "casearbejde, regneark, modellering og faglig fremlæggelse",
    ],
    productIdeas: [
      "strategiark med eksempler",
      "geometrisk model med forklaring",
      "datarapport med diagrammer",
      "problemløsningsposter",
      "forklaringsark med flere repræsentationer",
      "målerapport med metodevalg",
      "algebraisk mønsterforklaring",
      "casebesvarelse med beregninger og konklusion",
    ],
  },
  Engelsk: {
    commonGoalsIntro:
      "I engelsk arbejder eleverne med kommunikation, kultur og sprog. Årsplanen lægger op til mundtlighed, læsning, skrivning og møder med engelsksprogede kulturer.",
    courseIdeasByBand: {
      indskoling: [
        "Hello and colours",
        "Family and friends",
        "Songs, rhymes and movement",
        "Animals and my classroom",
        "Small stories",
        "My day",
      ],
      mellemtrin: [
        "My world",
        "London and landmarks",
        "Stories and characters",
        "Food and shopping",
        "Hobbies and school life",
        "Mini presentations",
      ],
      udskoling: [
        "Youth culture",
        "English-speaking countries",
        "Media and identity",
        "Global issues",
        "Opinion and argument",
        "Short fiction and themes",
      ],
    },
    courseIdeas: [
      "Everyday communication",
      "Stories and culture",
      "Write to be understood",
      "Global themes",
      "Voices from the English-speaking world",
      "Reading with strategies",
      "Opinion and argument",
      "Presentation project",
    ],
    focusAreas: [
      "ordforråd, udtale, samtalestrategier og tryg mundtlighed",
      "læsestrategier, tekstforståelse, kultur og personkarakteristik",
      "writing process, sentence starters, feedback and revision",
      "facts, opinions, argumentation and presentation language",
      "kulturmøder, perspektiver, lytteforståelse og samtale",
      "skimming, scanning, inference og tekstnære svar",
      "opinion phrases, examples, counterarguments and respectful debate",
      "research, structure, visuals and confident speaking",
    ],
    activityIdeas: [
      "pair talks, role cards, listening tasks and mini-presentations",
      "shared reading, vocabulary maps, discussion circles and writing prompts",
      "model texts, peer feedback, writing sprints and editing checklists",
      "short research, vocabulary bank, group talk and presentation practice",
      "video clips, culture cards, comparison tasks and spoken reflection",
      "reading stations, keyword notes, partner questions and exit tickets",
      "debate lines, argument cards, model phrases and short responses",
      "source work, rehearsal, slide planning and peer coaching",
    ],
    productIdeas: [
      "kort mundtlig præsentation på engelsk",
      "reading response med teksteksempler",
      "færdig kort tekst med refleksion",
      "gruppepræsentation på engelsk",
      "culture comparison poster",
      "reading journal entry",
      "opinion paragraph or mini debate",
      "presentation with visual support",
    ],
  },
  Tysk: {
    commonGoalsIntro:
      "I tysk arbejder eleverne med enkel kommunikation, kulturforståelse, ordforråd og sproglig nysgerrighed. Årsplanen fordeler mundtlige, skriftlige og kulturelle forløb i overskuelige perioder.",
    courseIdeasByBand: {
      mellemtrin: [
        "Hallo und ich",
        "Meine Familie",
        "Farben, Zahlen und Schule",
        "Essen und Freizeit",
        "Tyske byer for begyndere",
        "Min første dialog",
      ],
      udskoling: [
        "Jugend und Identität",
        "Deutschland heute",
        "Reisen und Alltag",
        "Meinungen und Argumente",
        "Kultur og medier",
        "Præsentation på tysk",
      ],
    },
    courseIdeas: [
      "Hallo und Alltag",
      "Meine Welt",
      "Essen, Freizeit und Gewohnheiten",
      "Tyske byer og kulturmøder",
      "Læsning med støtte",
      "Skriv korte tekster",
      "Mundtlig træning i par",
      "Miniprojekt på tysk",
    ],
    focusAreas: [
      "hilsner, basisordforråd, udtale og tryg deltagelse",
      "familie, interesser, beskrivelser og simple sætningsmønstre",
      "hverdagsemner, verber, chunks og korte dialoger",
      "kultur, geografi, sammenligning og præsentationssprog",
      "læsestrategier, transparente ord og billedstøtte",
      "sætningsstartere, ordstilling, respons og revision",
      "spørgsmål, svar, lytteforståelse og udtale",
      "research, produktvalg, fremlæggelse og sproglig sikkerhed",
    ],
    activityIdeas: [
      "lytteøvelser, samtalekort, gentagelsesrutiner og små rollespil",
      "ordbank, billedkort, makkerinterview og korte beskrivelser",
      "dialogøvelser, madkort, bevægelseslege og mini-skrivning",
      "kortarbejde, videoklip, kulturposter og fælles samtale",
      "tekstbidder, ordjagt, makkerlæsning og forståelsesspørgsmål",
      "modeltekster, skrivepar, responskort og omskrivning",
      "speed-dating, lytteopgaver, udtaletræning og korte optagelser",
      "projektværksted, billedstøtte, øvefremlæggelse og feedback",
    ],
    productIdeas: [
      "kort dialog med makker",
      "personlig præsentation med støtteord",
      "menu, dialog eller hverdagsplakat",
      "kulturposter med tyske nøgleord",
      "læseark med strateginoter",
      "kort tekst med respons",
      "mundtlig optagelse eller samtale",
      "miniprojekt med tysk præsentation",
    ],
  },
  Historie: {
    commonGoalsIntro:
      "I historie arbejder eleverne med at forstå sammenhænge mellem fortid, nutid og fremtid. Årsplanen lægger op til arbejde med historiske problemstillinger, kilder og elevernes historiske bevidsthed.",
    courseIdeasByBand: {
      mellemtrin: [
        "Vikingetiden",
        "Middelalderen",
        "Kilder og spor fra fortiden",
        "Danmark før og nu",
        "Konger, kirker og byer",
        "Hverdagsliv gennem tiden",
      ],
      udskoling: [
        "Demokrati og diktatur",
        "Industrialisering",
        "Danmark under besættelsen",
        "Den kolde krig",
        "Kildekritik og historiebrug",
        "Migration og kulturmøder",
      ],
    },
    courseIdeas: [
      "Historiske spor i hverdagen",
      "Magt, demokrati og rettigheder",
      "Danmark i verden",
      "Kilder og fortællinger",
      "Krig, fred og vendepunkter",
      "Levevilkår før og nu",
      "Historiebrug i medier",
      "Årets historiske undersøgelse",
    ],
    focusAreas: [
      "kildearbejde, kronologi og historiske spørgsmål",
      "årsag, virkning, begreber og historiske vendepunkter",
      "perspektivskifte, sammenhænge og historisk bevidsthed",
      "kildekritik, fortolkning og faglig argumentation",
      "brud, kontinuitet, aktører og konsekvenser",
      "levevilkår, sociale forskelle, hverdag og forandring",
      "historiebrug, fremstillinger, afsender og formål",
      "problemstilling, materialevalg, konklusion og formidling",
    ],
    activityIdeas: [
      "kildearbejde, tidslinjer, fortællinger og historiske problemstillinger",
      "billedanalyse, kildepar, årsagskæder og fælles samtaler",
      "kortarbejde, små undersøgelser, begrebskort og refleksionsskrivning",
      "kildeværksted, makkersamtaler, dramatisering og korte skriveøvelser",
      "tidslinjer, aktørkort, dilemmaøvelser og historisk debat",
      "sammenligning, elevinterview, arkivmateriale og klasseopsamling",
      "medieklip, monumenter, reklamer og kritisk samtale om historiebrug",
      "projektværksted, kildesøgning, vejledning og præsentation",
    ],
    productIdeas: [
      "visuel tidslinje med mundtlig forklaring",
      "gruppefremlæggelse med kilder",
      "faglig poster med historisk problemstilling",
      "historisk forklaring med kildehenvisninger",
      "årsagsforklaring eller historisk essay",
      "sammenlignende hverdagsfortælling",
      "analyse af historiebrug",
      "undersøgelsesprodukt med konklusion",
    ],
  },
  Samfundsfag: {
    commonGoalsIntro:
      "I samfundsfag arbejder eleverne med demokrati, politik, økonomi og sociale forhold. Årsplanen lægger op til, at eleverne undersøger aktuelle problemstillinger og lærer at argumentere fagligt.",
    courseIdeasByBand: {
      udskoling: [
        "Demokrati og magt",
        "Medier og holdninger",
        "Økonomi i hverdagen",
        "Unge, fællesskab og rettigheder",
        "Velfærd og prioriteringer",
        "Aktuel samfundsfaglig case",
      ],
    },
    courseIdeas: [
      "Demokrati og magt",
      "Medier og holdninger",
      "Økonomi i hverdagen",
      "Unge, fællesskab og rettigheder",
      "Velfærd og prioriteringer",
      "Kommunalpolitik tæt på",
      "Data, meninger og samfund",
      "Aktuel samfundsfaglig case",
    ],
    focusAreas: [
      "politiske begreber, aktuelle eksempler og argumentation",
      "kildekritik, argumenttyper og demokratisk samtale",
      "budget, skat, forbrug og samfundsøkonomiske valg",
      "sociologi, normer, fællesskaber og handlemuligheder",
      "velfærdsmodeller, rettigheder, pligter og prioritering",
      "kommunale opgaver, demokrati i praksis og lokal beslutningstagning",
      "dataforståelse, grafer, holdningsmålinger og fejlkilder",
      "problemstilling, aktører, interesser og løsningsforslag",
    ],
    activityIdeas: [
      "debatøvelser, casearbejde, kildearbejde og aktuelle eksempler",
      "nyhedsanalyse, debatkort, miniundersøgelser og redaktionelt værksted",
      "budgetcase, begrebstræning og fælles prioriteringsøvelser",
      "interviewspørgsmål, dataøvelser og rollespil med holdninger",
      "prioriteringskort, velfærdscases, paneldebat og fælles opsamling",
      "lokal case, kommunekort, udvalgsspil og kort argumentation",
      "diagramlæsning, meningsmålinger, klassedata og kritiske spørgsmål",
      "caseanalyse, aktørkort, løsningsforslag og fremlæggelse",
    ],
    productIdeas: [
      "gruppefremlæggelse",
      "kort argumenterende tekst",
      "debatoplæg",
      "undersøgelsesplakat",
      "prioriteringsoplæg med begrundelse",
      "lokalpolitisk minioplæg",
      "datafortolkning med kildekritik",
      "samfundsfaglig casepræsentation",
    ],
  },
  Kristendomskundskab: {
    commonGoalsIntro:
      "I kristendomskundskab arbejder eleverne med livsspørgsmål, etik, bibelske fortællinger, kristendom og andre religioner. Årsplanen lægger op til samtale, undersøgelse og respektfuld perspektivering.",
    courseIdeasByBand: {
      indskoling: [
        "Fortællinger og symboler",
        "Højtider og traditioner",
        "Venskab, valg og følelser",
        "Fortællinger fra Bibelen",
      ],
      mellemtrin: [
        "Livsspørgsmål og etik",
        "Kristendom i Danmark",
        "Religioner og ritualer",
        "Symboler, fortællinger og fællesskaber",
      ],
      udskoling: [
        "Etiske dilemmaer",
        "Religion i det moderne samfund",
        "Tro, identitet og livsvalg",
        "Religion, kultur og konflikt",
      ],
    },
    courseIdeas: [
      "Livsspørgsmål og etik",
      "Fortællinger og symboler",
      "Højtider og traditioner",
      "Religioner i hverdagen",
      "Tro, identitet og fællesskab",
      "Etiske dilemmaer",
      "Kulturmøder og respekt",
      "Årets refleksionsprojekt",
    ],
    focusAreas: [
      "livsspørgsmål, værdier, samtale og begrundede synspunkter",
      "fortællinger, symboler, fortolkning og faglige begreber",
      "traditioner, ritualer, fællesskaber og kulturel betydning",
      "religionsfaglige begreber, sammenligning og respektfuld nysgerrighed",
      "identitet, tro, tvivl, normer og fællesskab",
      "etik, dilemmaer, argumentation og perspektivskifte",
      "kulturmøder, minoriteter, medborgerskab og samtaleformer",
      "refleksion, formidling, spørgsmål og faglig opsamling",
    ],
    activityIdeas: [
      "samtalekort, fortællinger, billedanalyse og refleksionsøvelser",
      "begrebskort, små cases, makkerdialoger og fælles opsamling",
      "ritualværksted, tekstarbejde, sammenligning og klassesamtale",
      "dilemmakort, argumentationsøvelser, korte tekster og paneldialog",
      "interviewspørgsmål, kulturkort, fælles læsning og refleksionsnoter",
      "casearbejde, rollespil, stillingtagen og begrundede svar",
      "miniundersøgelser, præsentationer, respektfuld feedback og begrebsarbejde",
      "portfolio, elevsamtaler, afsluttende refleksion og mundtlig deling",
    ],
    productIdeas: [
      "refleksionsnotat",
      "symbolplakat med forklaring",
      "kort mundtlig præsentation",
      "etik-case med begrundelse",
      "sammenligningsark",
      "begrebskort",
      "gruppeoplæg om tradition eller ritual",
      "portfolio-side med livsspørgsmål",
    ],
  },
  Geografi: {
    commonGoalsIntro:
      "I geografi arbejder eleverne med naturgrundlag, levevilkår, kort, ressourcer og menneskers brug af verden. Årsplanen lægger op til undersøgelser, data, modeller og aktuelle geografiske problemstillinger.",
    courseIdeasByBand: {
      mellemtrin: [
        "Kort, steder og landskaber",
        "Vejr, klima og hverdagsliv",
        "Byer, land og ressourcer",
        "Danmark og verden",
      ],
      udskoling: [
        "Klima og klimaforandringer",
        "Befolkning og migration",
        "Ressourcer og bæredygtighed",
        "Globalisering og levevilkår",
      ],
    },
    courseIdeas: [
      "Kort og landskaber",
      "Vejr, klima og vand",
      "Befolkning og levevilkår",
      "Ressourcer og bæredygtighed",
      "Byudvikling og infrastruktur",
      "Naturkatastrofer og risici",
      "Globalisering og handel",
      "Geografisk feltarbejde",
    ],
    focusAreas: [
      "kortlæsning, stedbegreber, landskaber og geografiske mønstre",
      "vejrsystemer, klima, vandkredsløb og lokale eksempler",
      "befolkningstal, migration, levevilkår og forklarende data",
      "ressourceforbrug, bæredygtighed, interessekonflikter og handlemuligheder",
      "byrum, transport, arealanvendelse og planlægning",
      "risiko, naturprocesser, beredskab og konsekvenser",
      "handel, produktion, forbindelser og globale afhængigheder",
      "feltmetoder, observationer, kortdata og faglig konklusion",
    ],
    activityIdeas: [
      "kortøvelser, dataarbejde, modeltegning og casearbejde",
      "vejrobservationer, feltarbejde, diagrammer og forklaringsøvelser",
      "atlasarbejde, kildeanalyse, miniundersøgelser og klassedebat",
      "interessekort, bæredygtighedscases, gruppearbejde og præsentation",
      "lokal vandring, fotonoter, kortmarkeringer og byplanlægning",
      "modelbygning, risikokort, nyhedscases og faglig opsamling",
      "varekæder, rollespil, grafer og kort argumenterende tekst",
      "feltjournal, målinger, digitale kort og kort fremlæggelse",
    ],
    productIdeas: [
      "temakort med forklaring",
      "feltjournal",
      "datafortolkning med diagram",
      "bæredygtighedsplakat",
      "casefremlæggelse",
      "geografisk rapport",
      "kort video eller præsentation",
      "lokal undersøgelse med konklusion",
    ],
  },
  Biologi: {
    commonGoalsIntro:
      "I biologi arbejder eleverne med levende organismer, økosystemer, krop, sundhed, evolution og bæredygtighed. Årsplanen lægger op til forsøg, observationer, modeller og faglige forklaringer.",
    courseIdeasByBand: {
      mellemtrin: [
        "Dyr, planter og levesteder",
        "Kroppen og sundhed",
        "Små økosystemer",
        "Fødekæder og naturbalance",
      ],
      udskoling: [
        "Celler, gener og arv",
        "Økosystemer og biodiversitet",
        "Krop, sundhed og livsstil",
        "Evolution og tilpasning",
      ],
    },
    courseIdeas: [
      "Celler og livets byggesten",
      "Økosystemer og biodiversitet",
      "Krop, sundhed og livsstil",
      "Arv, gener og evolution",
      "Mikroorganismer og hygiejne",
      "Naturforvaltning og bæredygtighed",
      "Fødekæder og energistrømme",
      "Biologisk feltarbejde",
    ],
    focusAreas: [
      "organismer, celler, mikroskopi og biologiske fagord",
      "samspil, levesteder, biodiversitet og økologiske sammenhænge",
      "krop, sundhed, livsstil, data og kritisk stillingtagen",
      "arv, variation, tilpasning og evolutionære forklaringer",
      "mikroorganismer, smitteveje, forsøg og hygiejne",
      "bæredygtighed, naturforvaltning, interessekonflikter og handling",
      "fødekæder, stofkredsløb, energi og modeller",
      "feltmetoder, observationer, artsbestemmelse og konklusion",
    ],
    activityIdeas: naturalScienceActivities,
    productIdeas: naturalScienceProducts,
  },
  "Fysik/kemi": {
    commonGoalsIntro:
      "I fysik/kemi arbejder eleverne med stof, energi, kræfter, modeller og naturvidenskabelige arbejdsmetoder. Årsplanen lægger op til forsøg, målinger, forklaringer og koblinger til hverdagen.",
    courseIdeasByBand: {
      udskoling: [
        "Stoffer og reaktioner",
        "Energi og energiformer",
        "Elektricitet og kredsløb",
        "Lyd, lys og bølger",
        "Atomer og molekyler",
        "Klima, teknologi og energi",
      ],
    },
    courseIdeas: [
      "Stoffer og reaktioner",
      "Energi og energiformer",
      "Elektricitet og kredsløb",
      "Kræfter og bevægelse",
      "Lyd, lys og bølger",
      "Atomer og molekyler",
      "Syrer, baser og salte",
      "Teknologi og bæredygtighed",
    ],
    focusAreas: [
      "stoffers egenskaber, reaktioner, sikkerhed og faglige begreber",
      "energiovergange, målinger, modeller og hverdagskoblinger",
      "strøm, spænding, kredsløb og systematiske undersøgelser",
      "kraft, bevægelse, friktion og forklarende modeller",
      "bølger, sanser, målinger og teknologiske eksempler",
      "partikelmodeller, grundstoffer, molekyler og kemiske bindinger",
      "pH, indikatorer, reaktioner og anvendelse i hverdagen",
      "teknologi, energiressourcer, bæredygtighed og argumentation",
    ],
    activityIdeas: naturalScienceActivities,
    productIdeas: naturalScienceProducts,
  },
  "Natur/teknologi": {
    commonGoalsIntro:
      "I natur/teknologi arbejder eleverne undersøgende med natur, krop, teknologi, materialer og nære fænomener. Årsplanen lægger op til praktiske aktiviteter, observationer og enkle faglige forklaringer.",
    courseIdeasByBand: {
      indskoling: [
        "Dyr og planter omkring os",
        "Vejr og årstider",
        "Krop og sanser",
        "Materialer og byggeri",
      ],
      mellemtrin: [
        "Vand, vejr og klima",
        "Teknologi i hverdagen",
        "Kroppen og sundhed",
        "Naturens kredsløb",
        "Energi og enkle maskiner",
      ],
    },
    courseIdeas: [
      "Vand, vejr og årstider",
      "Dyr, planter og levesteder",
      "Krop, sanser og sundhed",
      "Materialer og konstruktion",
      "Energi i hverdagen",
      "Teknologi og opfindelser",
      "Naturens kredsløb",
      "Undersøgelse i lokalområdet",
    ],
    focusAreas: [
      "observationer, nysgerrighed, fagord og enkle forklaringer",
      "levesteder, tilpasning, sortering og naturfaglige spørgsmål",
      "sanser, krop, sundhed, data og hverdagsvaner",
      "materialers egenskaber, konstruktion, design og afprøvning",
      "energi, bevægelse, varme og hverdagseksempler",
      "teknologiforståelse, opfindelser, problemer og løsninger",
      "vand, næringsstoffer, livscyklusser og modeller",
      "feltarbejde, kortlægning, registrering og konklusion",
    ],
    activityIdeas: naturalScienceActivities,
    productIdeas: naturalScienceProducts,
  },
  Idræt: {
    commonGoalsIntro:
      "I idræt arbejder eleverne med alsidig bevægelse, kropslige færdigheder, samarbejde, fairplay og refleksion over sundhed og kropskultur. Årsplanen lægger op til variation mellem lege, teknik, spil og evaluering.",
    courseIdeasByBand: {
      indskoling: [
        "Motorik og bevægelsesglæde",
        "Lege, regler og samarbejde",
        "Rytme og balance",
        "Krop og sanser i bevægelse",
      ],
      mellemtrin: [
        "Boldbasis og fairplay",
        "Kropsbasis og redskaber",
        "Dans, rytme og udtryk",
        "Løb, spring og kast",
      ],
      udskoling: [
        "Spilforståelse og taktik",
        "Træning, sundhed og motivation",
        "Kropskultur og identitet",
        "Outdoor og samarbejde",
      ],
    },
    courseIdeas: [
      "Bevægelsesglæde og samarbejde",
      "Boldspil og fairplay",
      "Kropsbasis og redskaber",
      "Dans, rytme og udtryk",
      "Løb, spring og kast",
      "Træning og sundhed",
      "Outdoor og orientering",
      "Idrætskultur og refleksion",
    ],
    focusAreas: [
      "motorik, kropskontrol, samarbejde og tryg deltagelse",
      "spilregler, fairplay, teknik og fælles taktisk forståelse",
      "balance, styrke, rotation, sikkerhed og progression",
      "rytme, udtryk, koreografi og kropslig kommunikation",
      "teknik, måling, forbedring og personlig målsætning",
      "træningsprincipper, puls, motivation og sundhed",
      "orientering, natur, samarbejde og problemløsning",
      "idrætskultur, roller, normer og refleksion",
    ],
    activityIdeas: [
      "bevægelseslege, makkerøvelser, stationsbaner og fælles refleksion",
      "spiløvelser, regeljusteringer, små kampe og fairplay-samtaler",
      "redskabsbaner, tekniktræning, sikkerhedsmakker og progression",
      "rytmeøvelser, gruppeproduktion, visning og respons",
      "test, teknikstationer, målsætning og gentagen træning",
      "træningscirkel, pulsmåling, samtalekort og refleksionslog",
      "orienteringsopgaver, samarbejdsposter, kortlæsning og opsamling",
      "casekort, diskussion, elevvalg og kort præsentation",
    ],
    productIdeas: [
      "tekniklog eller bevægelsesportfolio",
      "gruppevisning eller lille turnering",
      "koreografi med respons",
      "personlig træningsplan",
      "fairplay-aftale",
      "orienteringsrute med refleksion",
      "mundtlig evaluering",
      "kort idrætsfaglig præsentation",
    ],
  },
  Musik: {
    commonGoalsIntro:
      "I musik arbejder eleverne med musikudøvelse, musikalsk skaben, lytning og musikkens betydning. Årsplanen lægger op til sammenspil, sang, rytme, kreativitet og refleksion.",
    courseIdeasByBand: {
      indskoling: [
        "Sang, puls og rytme",
        "Lyt og tegn musik",
        "Instrumenter omkring os",
        "Musiklege og bevægelse",
      ],
      mellemtrin: [
        "Sammenspil og roller",
        "Rytmeværksted",
        "Sang og stemme",
        "Komposition med enkle mønstre",
        "Musik fra verden",
      ],
      udskoling: [
        "Bandforløb og arrangement",
        "Musikproduktion",
        "Musik, identitet og kultur",
        "Analyse af genre og virkemidler",
      ],
    },
    courseIdeas: [
      "Sang, puls og rytme",
      "Sammenspil og roller",
      "Musikalsk skaben",
      "Lytning og analyse",
      "Musik fra verden",
      "Instrumentkendskab",
      "Musikproduktion",
      "Koncert og evaluering",
    ],
    focusAreas: [
      "puls, rytme, stemmebrug og tryg deltagelse",
      "sammenspil, roller, timing og fælles ansvar",
      "motiver, form, gentagelse og kreative valg",
      "genre, instrumenter, dynamik og lytteopmærksomhed",
      "kultur, traditioner, udtryk og musikalsk nysgerrighed",
      "klang, instrumentfamilier, spilleteknik og notation",
      "loops, lydlag, struktur og digital musikskabelse",
      "øverutiner, performance, respons og refleksion",
    ],
    activityIdeas: [
      "fællessang, rytmelege, bodypercussion og lytteøvelser",
      "sammenspil, gruppeøvelser, stop-start-træning og respons",
      "kompositionskort, lydværksted, improvisation og optagelse",
      "lytteguide, genrejagt, samtale og korte notater",
      "musikeksempler, kulturkort, bevægelse og klasseopsamling",
      "instrumentstationer, notation, makkertræning og minikoncert",
      "digitalt værksted, loops, feedback og færdiggørelse",
      "øveplan, generalprøve, koncert og mundtlig evaluering",
    ],
    productIdeas: [
      "kort sammenspilsnummer",
      "rytme- eller lydkomposition",
      "lyttelog",
      "gruppeoptræden",
      "musikplakat med genretræk",
      "digital lydproduktion",
      "øvelog med refleksion",
      "minikoncert med respons",
    ],
  },
  Billedkunst: {
    commonGoalsIntro:
      "I billedkunst arbejder eleverne med billedfremstilling, billedanalyse og visuel kommunikation. Årsplanen lægger op til undersøgende processer, materialer, teknikker og samtale om visuelle udtryk.",
    courseIdeasByBand: {
      indskoling: [
        "Farver, former og fantasi",
        "Tegn det du ser",
        "Mønstre og materialer",
        "Billeder fortæller",
      ],
      mellemtrin: [
        "Farve, form og komposition",
        "Portræt og identitet",
        "Rum, perspektiv og skygge",
        "Billedfortælling og tegneserie",
        "Skulptur og materialer",
      ],
      udskoling: [
        "Visuel kommunikation",
        "Kunst, identitet og samfund",
        "Fotografi og iscenesættelse",
        "Designproces og udstilling",
      ],
    },
    courseIdeas: [
      "Farve, form og komposition",
      "Tegning og iagttagelse",
      "Billedfortælling",
      "Skulptur og materialer",
      "Kunstmøder og analyse",
      "Visuel kommunikation",
      "Fotografi og digitale billeder",
      "Udstilling og evaluering",
    ],
    focusAreas: [
      "farvelære, form, komposition og visuelle valg",
      "iagttagelse, skitse, proportioner og forbedring",
      "sekvens, fortælling, symboler og modtagerblik",
      "materialer, konstruktion, rumlighed og taktil erfaring",
      "kunstbegreber, analyse, fortolkning og samtale",
      "budskab, layout, typografi og visuel kommunikation",
      "fotografi, udsnit, lys, iscenesættelse og digital bearbejdning",
      "kuratering, respons, proces og faglig refleksion",
    ],
    activityIdeas: [
      "skitseøvelser, materialeforsøg, billedsamtaler og proceslog",
      "iagttagelsestegning, feedback, tekniktræning og forbedring",
      "storyboard, collage, tegneserieproduktion og responsrunde",
      "værkstedsarbejde, konstruktion, materialevalg og udstilling",
      "kunstkort, museumsblik, analyseøvelser og fælles samtale",
      "plakatværksted, layoutskitser, peer feedback og justering",
      "fotoopgaver, billedudvælgelse, redigering og refleksion",
      "udstillingsplan, titeltekster, fernisering og evaluering",
    ],
    productIdeas: [
      "billedserie med procesnoter",
      "tegning med før- og efterrefleksion",
      "tegneserie eller collage",
      "skulptur med materialeforklaring",
      "kort billedanalyse",
      "plakat eller visuel kampagne",
      "fotoprojekt med titeltekst",
      "miniudstilling med respons",
    ],
  },
  "Håndværk og design": {
    commonGoalsIntro:
      "I håndværk og design arbejder eleverne med designprocesser, materialer, teknikker, funktion og æstetik. Årsplanen lægger op til idéudvikling, afprøvning, produktion og evaluering.",
    courseIdeasByBand: {
      mellemtrin: [
        "Materialer og værktøj",
        "Design en brugsting",
        "Tekstil, træ og konstruktion",
        "Fra ide til produkt",
      ],
      udskoling: [
        "Designproces og brugerbehov",
        "Bæredygtigt produktdesign",
        "Prototype og forbedring",
        "Æstetik, funktion og formidling",
      ],
    },
    courseIdeas: [
      "Materialer og værktøj",
      "Designproces fra ide til produkt",
      "Tekstil, træ og konstruktion",
      "Bæredygtigt design",
      "Prototype og forbedring",
      "Funktion, form og æstetik",
      "Brugerbehov og målgruppe",
      "Udstilling og evaluering",
    ],
    focusAreas: [
      "materialekendskab, sikkerhed, værktøj og grundteknikker",
      "ideudvikling, skitser, kriterier og designvalg",
      "konstruktion, samlinger, tekstile teknikker og præcision",
      "genbrug, ressourcebevidsthed, holdbarhed og æstetik",
      "afprøvning, fejl, justering og forbedring",
      "funktion, form, farver, proportioner og brugsværdi",
      "målgruppe, behov, interview og designbrief",
      "procesformidling, respons, produktvurdering og udstilling",
    ],
    activityIdeas: [
      "materialestationer, sikkerhedsrutiner, teknikøvelser og proceslog",
      "skitsearbejde, moodboards, kriteriekort og makkerfeedback",
      "værkstedsproduktion, afprøvning, vejledning og justering",
      "genbrugscases, materialevalg, prototype og fælles kritik",
      "test med brugere, forbedringsrunde, fotodokumentation og refleksion",
      "formstudier, farvevalg, funktionsprøver og faglig samtale",
      "interview, brugerrejse, designbrief og ideudvælgelse",
      "udstillingsbord, titeltekst, responsrunde og evaluering",
    ],
    productIdeas: [
      "funktionel prototype",
      "designmappe med skitser",
      "brugsting med proceslog",
      "bæredygtigt produktforslag",
      "forbedret prototype",
      "produkt med brugerforklaring",
      "designbrief og løsningsforslag",
      "udstilling med evaluering",
    ],
  },
  Madkundskab: {
    commonGoalsIntro:
      "I madkundskab arbejder eleverne med madlavning, råvarer, måltider, sundhed, fødevarebevidsthed og madkultur. Årsplanen lægger op til praktisk arbejde, smag, samarbejde og faglig refleksion.",
    courseIdeasByBand: {
      mellemtrin: [
        "Køkkenrutiner og sikkerhed",
        "Smag, sanser og råvarer",
        "Måltider i hverdagen",
        "Madkultur og traditioner",
      ],
      udskoling: [
        "Sundhed, valg og vaner",
        "Bæredygtige måltider",
        "Madkultur og identitet",
        "Fra opskrift til eget måltid",
      ],
    },
    courseIdeas: [
      "Køkkenrutiner og sikkerhed",
      "Smag, sanser og råvarer",
      "Sundhed og måltider",
      "Madkultur og traditioner",
      "Bæredygtige valg",
      "Fra opskrift til eget måltid",
      "Fødevarebevidsthed",
      "Måltidsprojekt og evaluering",
    ],
    focusAreas: [
      "hygiejne, sikkerhed, samarbejde og køkkenrutiner",
      "smagssanser, råvarekendskab, tilsmagning og fagord",
      "kostråd, måltidsbalance, vaner og kritisk stillingtagen",
      "traditioner, kultur, identitet og fælles måltider",
      "sæson, madspild, bæredygtighed og ressourcevalg",
      "opskriftlæsning, metode, kreativitet og tilpasning",
      "fødevarer, mærkning, produktion og forbrugerbevidsthed",
      "planlægning, produktion, præsentation og evaluering",
    ],
    activityIdeas: [
      "praktisk madlavning, hygiejnerutiner, samarbejdsaftaler og smagning",
      "råvarestationer, sanseøvelser, tilsmagning og korte notater",
      "måltidsanalyse, opskriftsarbejde, gruppeproduktion og refleksion",
      "kulturcases, fælles madlavning, samtale og præsentation",
      "sæsonkort, madspildsøvelser, bæredygtighedscases og planlægning",
      "opskriftsvariation, testsmagning, feedback og justering",
      "mærkningsjagt, varekendskab, diskussion og forbrugeropgave",
      "projektkøkken, servering, evaluering og proceslog",
    ],
    productIdeas: [
      "måltid med kort faglig forklaring",
      "smagsnotat",
      "opskriftskort med variation",
      "måltidsanalyse",
      "bæredygtig menu",
      "kulturmåltid med præsentation",
      "forbrugerplakat",
      "madprojekt med evaluering",
    ],
  },
};

export const fallbackProfile: SubjectProfile = {
  commonGoalsIntro: genericCommonGoalsIntro,
  courseIdeas: [
    "Faglig opstart og fælles sprog",
    "Undersøgelse og fordybelse",
    "Anvendelse i praksis",
    "Perspektiv og evaluering",
    "Faglige metoder i brug",
    "Kreativt eller praktisk produkt",
    "Samarbejde og formidling",
    "Årets afsluttende opsamling",
  ],
  focusAreas: [
    "fagord, nysgerrighed, fælles rutiner og tryg deltagelse",
    "metoder, faglige spørgsmål og begrundede svar",
    "anvendelse, samarbejde, problemløsning og faglig præcision",
    "refleksion, evaluering, perspektivering og faglig samtale",
    "faglige arbejdsmåder, modeller og systematisk undersøgelse",
    "produktudvikling, feedback og tydelig faglig kobling",
    "kommunikation, samarbejdsroller og faglig formidling",
    "portfolio, repetition, valg af eksempler og elevrefleksion",
  ],
  activityIdeas: [
    "begrebskort, makkerøvelser, korte undersøgelser og fælles opsamling",
    "stationsarbejde, kildemateriale, samtalekort og fælles refleksion",
    "casearbejde, små produktioner, fælles feedback og afprøvning",
    "elevsamtaler, portfolio, korte præsentationer og fælles evaluering",
    "værkstedsopgaver, modeller, tjekspørgsmål og makkerforklaringer",
    "skitsefase, prototype, responsrunde og justering",
    "gruppeopgaver, rollefordeling, træning og fremlæggelse",
    "opsamlingsspil, portfolioarbejde, mini-samtaler og evaluering",
  ],
  productIdeas: [
    "fælles faglig begrebsvæg",
    "kort fagligt notat eller visuel forklaring",
    "praktisk produkt med kort forklaring",
    "portfolio-side eller afsluttende præsentation",
    "metodeark med eksempler",
    "produkt med responslog",
    "kort gruppefremlæggelse",
    "årsrefleksion med faglige eksempler",
  ],
};
